### ISSUE TITLE
ArangoDB crashes when I try to install the connector

### ISSUE THREAD

**Issue by vanthome** [arangodb/tableau-arangodb-wdc#2]
I'm running `3.8.5.1` and on installing via:

```
npx foxx-cli install -u root -P -H http://localhost:8529 -D master-data-srv /tableau
```

it crashes and I see this in the logs:

```
a-arangodb         | 2022-02-13T09:47:26Z [1] WARNING [514da] {general} Service at "/tableau" specifies unknown manifest field "0".
a-arangodb         | 2022-02-13T09:47:26Z [1] WARNING [514da] {general} Service at "/tableau" specifies unknown manifest field "1".
a-arangodb         | 2022-02-13T09:47:26Z [1] WARNING [514da] {general} Service at "/tableau" specifies unknown manifest field "2".
a-arangodb         | 2022-02-13T09:47:26Z [1] WARNING [514da] {general} Service at "/tableau" specifies unknown manifest field "3".
a-arangodb         | 2022-02-13T09:47:26Z [1] WARNING [514da] {general} Service at "/tableau" specifies unknown manifest field "4".
a-arangodb         | 2022-02-13T09:47:26Z [1] WARNING [514da] {general} Service at "/tableau" specifies unknown manifest field "5".
a-arangodb         | 2022-02-13T09:47:26Z [1] WARNING [514da] {general} Service at "/tableau" specifies unknown manifest field "6".
a-arangodb         | 2022-02-13T09:47:26Z [1] WARNING [514da] {general} Service at "/tableau" specifies unknown manifest field "7".
a-arangodb         | 2022-02-13T09:47:26Z [1] WARNING [514da] {general} Service at "/tableau" specifies unknown manifest field "8".
a-arangodb         | 2022-02-13T09:47:26Z [1] WARNING [514da] {general} Service at "/tableau" specifies unknown manifest field "9".
a-arangodb         | 2022-02-13T09:47:26Z [1] WARNING [514da] {general} Service at "/tableau" specifies unknown manifest field "10".
a-arangodb exited with code 137
```

**Comment by vanthome** [comment]
I have tried again with Version `3.9.0` and there I get:

```
Sorry! An unexpected error occurred. This is likely a bug in foxx-cli.
Please open an issue at https://github.com/arangodb/foxx-cli/issues with a full copy of the following error message and a description of what you were trying to do when this problem occurred.

HttpError: Payload Too Large
    at new HttpError (/home/thoppe/.npm/_npx/1f589f9261df1da2/node_modules/arangojs/error.js:154:21)
    at Object.resolve (/home/thoppe/.npm/_npx/1f589f9261df1da2/node_modules/arangojs/connection.js:452:37)
    at callback (/home/thoppe/.npm/_npx/1f589f9261df1da2/node_modules/arangojs/connection.js:210:26)
    at IncomingMessage.<anonymous> (/home/thoppe/.npm/_npx/1f589f9261df1da2/node_modules/arangojs/lib/request.node.js:108:21)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

We apologize for the inconvenience.

**Comment by pluma** [comment]
> `npx foxx-cli install -u root -P -H http://localhost:8529 -D master-data-srv /tableau`

Assuming `master-data-srv` is your local copy of the service and `/tableau` is supposed to be the mount point, I think you may have the order of your arguments inverted. The example given in the CLI help is:

> `foxx install /hello /tmp/my-service`

**Comment by vanthome** [comment]
@pluma no, that's wrong, I had the correct order. I could now install the extension via the Web UI but I'm now stuck with this error:

![image](https://user-images.githubusercontent.com/3037439/191022024-4de0a3c0-eac0-43e1-905b-7217c31f9cc3.png)

Ofc I have enabled AuthN and have a user created but it always tells me "Invalid Credentials". Any idea?
